# Generated by Django 5.2.4 on 2025-07-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=30)),
                ('em', models.CharField(max_length=30)),
                ('mo', models.CharField(max_length=30)),
                ('ps', models.CharField(max_length=30)),
                ('cps', models.CharField(max_length=30)),
            ],
        ),
    ]
