# Generated by Django 5.2.4 on 2025-07-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
