# Generated by Django 5.2.4 on 2025-08-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_myadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAdmin',
        ),
        migrations.AddField(
            model_name='plant',
            name='add',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
