# Generated by Django 5.2.4 on 2025-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0003_delete_myadmin_plant_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='fed',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='add',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
    ]
