# Generated by Django 5.2.4 on 2025-08-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0004_plant_fed_alter_plant_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='fedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=30)),
                ('em', models.CharField(max_length=30)),
                ('fed', models.CharField(default='Not Provided', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='fed',
        ),
    ]
