# Generated by Django 5.2.4 on 2025-08-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0005_fedback_remove_plant_fed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='add',
        ),
        migrations.AddField(
            model_name='fedback',
            name='add',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
    ]
