# Generated by Django 5.2.4 on 2025-08-14 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0006_remove_plant_add_fedback_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fedback',
            name='add',
        ),
    ]
