# Generated by Django 5.2.4 on 2025-08-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0007_remove_fedback_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fedback',
            name='em',
        ),
        migrations.RemoveField(
            model_name='fedback',
            name='nm',
        ),
    ]
