# Generated by Django 5.2.4 on 2025-08-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0008_remove_fedback_em_remove_fedback_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='fedback',
            name='email',
            field=models.CharField(default='Not Provided', max_length=30),
        ),
        migrations.AddField(
            model_name='fedback',
            name='name',
            field=models.CharField(default='Not Provided', max_length=30),
        ),
    ]
