# Generated by Django 5.2.4 on 2025-08-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0009_fedback_email_fedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedback',
            name='email',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='fedback',
            name='fed',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='fedback',
            name='name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
