# Generated by Django 5.2.4 on 2025-08-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0010_alter_fedback_email_alter_fedback_fed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=30)),
                ('email', models.CharField(default=' ', max_length=30)),
                ('add', models.CharField(default=' ', max_length=100)),
            ],
        ),
    ]
