# Generated by Django 5.2.4 on 2025-08-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0011_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
    ]
