# Generated by Django 5.2.4 on 2025-08-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0012_remove_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='add',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
