# Generated by Django 5.2.4 on 2025-08-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0013_alter_address_add_alter_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='add',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
